### PR TITLE
include dataclasses in py36 for run_test and smoke_test

### PR DESCRIPTION
**Pull request by walterddr**
Fix installation issue for dataclasses when running tests.

### CODE REVIEW

**Review by seemethere — COMMENTED** [review]
Would this also work for windows since windows uses `windows/internal/smoke_test.bat`?

**Comment by walterddr** [comment]
looks like windows conda is using build_pytorch.sh (then run_test.sh) see: https://github.com/pytorch/builder/blob/master/windows/internal/build_conda.bat yes?

**Comment by walterddr** [comment]
oops. you are right. this is next - once binary_windows_conda_xxx build passes, it needs to run smoke_test.bat... didn't think that far. good catch!!!

**Comment by walterddr** [comment]
closing in favor of #552

**Pull request closed without merging**
