### PR TITLE
[Validation] Pass ref:main to general worker

### PR DESCRIPTION
**Pull request by atalman**
Pass ref:main to general worker

### CODE REVIEW

**Review by seemethere — APPROVED** [review]

**Review by seemethere — CHANGES_REQUESTED** [review]
I think this might be wrong, do you actually want this? You still need some way to test this on pull requests here in builder wouldn't you?

If you hard code this here you wouldn't actually be able to test any changes

**Comment by atalman** [comment]
> I think this might be wrong, do you actually want this? You still need some way to test this on pull requests here in builder wouldn't you?
> 
> If you hard code this here you wouldn't actually be able to test any changes

Hm, we normally run these on workflow_call or workflow_dispatch, let me see what I can do here

**Comment by seemethere** [comment]
> > I think this might be wrong, do you actually want this? You still need some way to test this on pull requests here in builder wouldn't you?
> > If you hard code this here you wouldn't actually be able to test any changes
> 
> Hm, we normally run these on workflow_call or workflow_dispatch, let me see what I can do here

oh if that's the case then maybe we don't, but just wanted to call that out as a particular deficiency

**Review by seemethere — APPROVED** [review]

**Review by seemethere — APPROVED** [review]

**Comment by malfet** [comment]
Hmm, how are we testing those workflows?
As https://github.com/pytorch/builder/actions/runs/3519117049/jobs/5898729279 indicates that our Python-1.13+CUDA-11.7  PyPI wheels are not what we claim they are? Is this something we must fix ASAP? Or just a false positive and all those results could be ignored?

**Pull request merged**
