### PR TITLE
Add Windows Arm64 scripts

### PR DESCRIPTION
**Pull request by iremyux**
This PR adds the scripts necessary for a successful Windows Arm64 build. 
The nightly Windows Arm64 workflows using the scripts of this PR can be found on this draft PR to pytorch/pytorch : https://github.com/pytorch/pytorch/pull/139760

### CODE REVIEW

**Comment by atalman** [comment]
Hi @iremyux could you please add Workflow and move the PR to pytorch/pytorch ? Please use this runner: windows-11-arm64

**Comment by iremyux** [comment]
> Hi @iremyux could you please add Workflow and move the PR to pytorch/pytorch ? Please use this runner: windows-11-arm64 . Thank you.

Hey @atalman we actually have the draft PR to pytorch/pytorch ready. I've been using the windows-11-arm64 runners already. Here is the link : https://github.com/pytorch/pytorch/pull/139760 
But we're using the scripts on this fork, shouldn't this one to pytorch/builder get merged first?

**Comment by atalman** [comment]
hi @iremyux This is great! Thank you. Please move these scripts to the pytorch/pytorch PR. This is where linux aarch64 scripts live : https://github.com/pytorch/pytorch/tree/main/.ci/aarch64_linux

**Comment by iremyux** [comment]
@atalman I see, I was not aware of that. The other platforms are still using builder, hence this PR. I'll prepare the new one & will ask for a review afterwards. Thanks for the quick reply. Should I close this PR?

**Review by seemethere — APPROVED** [review]

**Comment by atalman** [comment]
Please note we are currently moving Windows scripts to pytorch/pytorch: https://github.com/pytorch/pytorch/pull/142156

**Pull request merged**
