### PR TITLE
Added small fix for LTS builds in smoke testing stage

### PR DESCRIPTION
**Pull request by mstfbl**
Unconditionally install numpy for caffe2 testing

### CODE REVIEW

**Comment by malfet** [comment]
Can you please share a link to the failing test?

**Comment by mstfbl** [comment]
@malfet Sure, [here ](https://app.circleci.com/pipelines/github/pytorch/pytorch/409789/workflows/9f84dfcc-1ad9-4108-9e1a-985be6f3ee0d)is one of the latest LTS binary build workflows. There are 11 Windows and 1 MacOS builds failing, and they're all due to the `python -c 'from caffe2.python import core'` line throwing the "ModuleNotFoundError: No module named 'numpy'" error, as can be seen in [this ](https://app.circleci.com/pipelines/github/pytorch/pytorch/409789/workflows/9f84dfcc-1ad9-4108-9e1a-985be6f3ee0d/jobs/16726521?invite=true#step-106-2990)sample error. [This line](https://github.com/pytorch/builder/blob/777174a0392003ef17dfa34c7944def8e8567ef3/run_tests.sh#L90) to install `numpy` is doing it silently, but clearly numpy isn't being installed correctly.

**Comment by malfet** [comment]
@mstfbl 
Code that your are touching is part of else block of the following if statement
https://github.com/pytorch/builder/blob/4a341b1a0ac3c3e5d328b8df047e3a14849a9b21/run_tests.sh#L63
so I'm not seeing how changing numpy version from 1.15 to 1.19 would have any effect on the failures your are trying to fix.

Small debugging tip: Lines in a log that start with `+` are the code lines of the script being executed.
For example from [binary_windows_conda_3_7_cu102_nightly_build](https://app.circleci.com/pipelines/github/pytorch/pytorch/409789/workflows/9f84dfcc-1ad9-4108-9e1a-985be6f3ee0d/jobs/16726503) log
```
+ [[ conda == conda ]]
+ [[ cu102 = \c\p\u ]]
+ retry conda update -yq --all -c defaults -c pytorch -c numba/label/dev
+ conda update -yq --all -c defaults -c pytorch -c numba/label/dev
```
That line 63 were evaluated to true, then line 72 to false, which results in execution of lines 77 and 80 and then line 83 were not executed as condition on line 81 were false

If you want to fix those failures, most likely all you need to do is to remove the following condition on line 81
https://github.com/pytorch/builder/blob/4a341b1a0ac3c3e5d328b8df047e3a14849a9b21/run_tests.sh#L81

**Review by malfet — CHANGES_REQUESTED** [review]
Requesting changes as proposed PR does not fix smoke tests

**Comment by mstfbl** [comment]
Thank you @malfet for the explanation and suggestion. I have applied your suggested fix to this PR.

**Review by malfet — APPROVED** [review]
@mstfbl looks good to me, but please change PR title/description to match the changes you made (as "Install NumPy 1.19 for smoke testing" sounds like a confusing statement at this point)

**Comment by malfet** [comment]
Manually editing commit message and merging...

**Pull request merged**
