### PR TITLE
[ROCm] add dependencies for rocm5.2

### PR DESCRIPTION
**Pull request by jeffdaily**

### CODE REVIEW

**Review by jithunnair-amd — APPROVED** [review]

**Review by janeyx99 — APPROVED** [review]
Could I get some context about moving to 5.2?

**Comment by janeyx99** [comment]
Also, before we merge this, can we verify it passes CI?

**Comment by jithunnair-amd** [comment]
> Could I get some context about moving to 5.2?

It's the latest ROCm version that was released. We always strive to keep the nightly binary builds on the latest ROCm release.

**Comment by jithunnair-amd** [comment]
@janeyx99 Please let us know if we need something more in this PR to merge it. The pytorchbot command doesn't work on builder repo I think.
cc @seemethere

**Comment by janeyx99** [comment]
merged

**Comment by jeffdaily** [comment]
@janeyx99 On the corresponding pytorch PR I'm getting build failures for rocm 5.2 binaries because the docker image is missing. 

pytorch/manylinux-builder:rocm5.2

How can we trigger a build and push of this image?  I thought this current PR should have done that.

**Comment by janeyx99** [comment]
@jeffdaily  it looks liek the corresponding actions timed out https://github.com/pytorch/builder/actions/runs/2733195759

**Comment by jeffdaily** [comment]
> @jeffdaily it looks liek the corresponding actions timed out https://github.com/pytorch/builder/actions/runs/2733195759

Looks like rocm base image builds need more time.  Can we increase the timeout?  We need these images for nightly pytorch binaries.

**Comment by jeffdaily** [comment]
@janeyx99 but the latest CI runs were all successful.  Not sure why they timed out for the run you linked to.

https://github.com/pytorch/builder/pull/1033/checks?check_run_id=7201495074

**Pull request merged**
