### PR TITLE
[aarch64] cherry-pick Xbyak crash fix and linter error fixes from main

### PR DESCRIPTION
**Pull request by snadampal**
cc: @atalman

### CODE REVIEW

**Review by malfet — CHANGES_REQUESTED** [review]
This is not a cherry-pick of above-mentioned commit, is it?

**Comment by snadampal** [comment]
hi @malfet this is a cherrypick of 4 commits from main. I picked all 4 so that they apply cleanly.
do you mean (1) let's pick only the last one and rework it to apply on 2.2 branch? or 
(2) pick only the subset of changes went into xbyak repo? https://github.com/fujitsu/xbyak_aarch64/pull/96

**Comment by atalman** [comment]
@snadampal Could you please mention all 4 cherry-picks in the issue tracker here: https://github.com/pytorch/pytorch/issues/115300#issuecomment-1867002507 this way we are sure which commits are getting cherry-picked

**Comment by snadampal** [comment]
Hi @malfet , @atalman , updated the tracker with all the 4 commits.

**Review by atalman — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Pull request merged**
