### PR TITLE
PR: Add FFmpeg recipe to builder

### PR DESCRIPTION
**Pull request by andfoy**
This PR adds ffmpeg to the pytorch conda channel in order to be used by torchvision. GPL and static components were disabled in order to prevent licensing issues.

cc @fmassa, @seemethere

### CODE REVIEW

**Comment by andfoy** [comment]
I tested this PR locally on Linux, and it works as expected

**Comment by andfoy** [comment]
I've also tested locally on Windows, and it also works

**Comment by seemethere** [comment]
I can build the packages for these for linux, but I don't think I have a windows machine on hand

**Comment by andfoy** [comment]
> I can build the packages for these for linux, but I don't think I have a windows machine on hand

@seemethere  I have a Windows VM, please let me know if that works

**Pull request merged**
