### PR TITLE
[aarch64] acl build script updates for multi isa build with armv8-a base architecture

### PR DESCRIPTION
**Pull request by snadampal**
This PR fixes the issue https://github.com/pytorch/pytorch/issues/97226

### CODE REVIEW

**Comment by snadampal** [comment]
Here is the ACL github issue to check if this can be made default in the ACL build system:
https://github.com/ARM-software/ComputeLibrary/issues/1046

**Comment by snadampal** [comment]
Hi @malfet , updated the PR to modify the build files with "sed" directly, instead of the explicit patch. Please let me know  if there is any feedback.

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
Thank you very much for the fix. Merged

**Comment by snadampal** [comment]
great! thanks for merging it @malfet .

**Pull request merged**
