### PR TITLE
Disable TESTS for static library builds

### PR DESCRIPTION
**Pull request by makslevental**
Working version of https://github.com/pytorch/builder/pull/1068

### CODE REVIEW

**Comment by makslevental** [comment]
@malfet tested again pytorch tip 

https://github.com/pytorch/pytorch/pull/80470

by swapping the builder repo with mine here

https://github.com/pytorch/pytorch/pull/80470/files

**Comment by malfet** [comment]
@makslevental you've forgot to add `ciflow/binaries` to the test PR, done it already, so if say https://github.com/pytorch/pytorch/runs/7102907979?check_suite_focus=true it would be good to go

**Comment by makslevental** [comment]
> @makslevental you've forgot to add `ciflow/binaries` to the test PR, done it already, so if say https://github.com/pytorch/pytorch/runs/7102907979?check_suite_focus=true it would be good to go

Thanks I wasn't aware of that label. I'll watch the tests to make sure they pass.

**Comment by malfet** [comment]
Reverting the change, as pytorch PR that you've authored did not really tested anything:
- you've modified template for mac builds, while this change targets Linux ones,  also you have not re-run regenerate.sh as lint suggested you should have done for the change to take [effect](https://github.com/pytorch/pytorch/runs/7100240918?check_suite_focus=true#step:7:489):
>As shown by the above diff, the committed .github/workflows
>are not up to date according to .github/templates.
>Please run this command, commit, and push again to your PR:

**Pull request merged**
