### PR TITLE
Update cudnn to 8.7.0.84 for CUDA 11.8 builds

### PR DESCRIPTION
**Pull request by ptrblck**
CC @atalman @malfet

### CODE REVIEW

**Comment by aifartist** [comment]
Will this also be done for the Torch 2.0 nightly builds?  I would think you won't want the newer Torch (2) to be using older versions of cuDNN than the older Torch that this PR will fix.

**Comment by ptrblck** [comment]
Yes, this PR updates cudNN to 8.7.0.84 for all CUDA 11.8 Linux builds, which are only available as the nightly binaries and will thus show up as `torch==2.0.0devDATE`. 
Note that updating cuDNN was already on our roadmap, but after the full testing of the 11.8 + `sm_90` builds.
We are still debugging [this PR](https://github.com/pytorch/pytorch/pull/92137) which seems to fail for some Windows jobs, but decided to go ahead with the cuDNN update for Linux due to the perf. improvements you were seeing in https://github.com/pytorch/pytorch/issues/92288.
We will follow up with Windows builds once we fix the failing tests in the related PR.

**Comment by aifartist** [comment]
> Yes, this PR updates cudNN to 8.7.0.84 for all CUDA 11.8 Linux builds, which are only available as the nightly binaries and will thus show up as `torch==2.0.0devDATE`.
Not everyone is willing to install a pre-release still in devlopment Torch 2.  If Torch 1.31.1+cu118 is frozen will there be a 1.13.2 with the fix or does 1.31.next still have a nightly build where people can get this in an existing 1.13 base of PyTorch?  Otherwise they'.. have to wait till ?Mar? for the new Torch 2 GA.

**Comment by ptrblck** [comment]
> If Torch 1.31.1+cu118 is frozen will there be a 1.13.2 with the fix or does 1.31.next still have a nightly build where people can get this in an existing 1.13 base of PyTorch?

I don't know if `1.13.2` is planned, but I haven't heard about any plans to release it.

> Otherwise they'll have to wait till ?Mar? for the new Torch 2 GA.

Yes, I would assume users not willing to install the nightly release would have to wait for the next "stable" release.

I'll also let @malfet comment on it as the release manager.

**Comment by atalman** [comment]
> > Yes, this PR updates cudNN to 8.7.0.84 for all CUDA 11.8 Linux builds, which are only available as the nightly binaries and will thus show up as `torch==2.0.0devDATE`.
> 
> Not everyone is willing to install a pre-release still in devlopment Torch 2. If Torch 1.31.1+cu118 is frozen will there be a 1.13.2 with the fix or does 1.31.next still have a nightly build where people can get this in an existing 1.13 base of PyTorch? Otherwise they'll have to wait till ?Mar? for the new Torch 2 GA.

@aifartist @ptrblck So far no 1.13.2 is planned. Minor releases are performed only for hi priority critical fixes. Dependency updates similar to this are only done for major releases.

**Comment by johnnynunez** [comment]
> 

And it is not possible for pytorch nightly?
NGC Nvidia-Pytorch release use this cudnn without problems: https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-22-12.html#rel-22-12

**Comment by ptrblck** [comment]
> And it is not possible for pytorch nightly?

This PR is targeting the 11.8 nightlies.

**Comment by aifartist** [comment]
> > 
> 
> And it is not possible for pytorch nightly? NGC Nvidia-Pytorch release use this cudnn without problems: https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-22-12.html#rel-22-12

Egads.  Not another completing version of a product from a 2nd source!.  Now I have to figure out how NVidia's PyTorch 22.12 compares with PyTorch.org's 2.0.0.

I will say that I haven't had success building pytorch with TensorRT.  Given that this is available I want to try it.  Sigh, I guess I will have to install docker.  Yet another infrastructure/religion claiming to be the best.

Damn.  I just read it says Ubuntu 20.04.  I have 22.04.

**Comment by atalman** [comment]
@ptrblck I think windows CI was merged we can propose the windows change here as well, like this: https://github.com/pytorch/builder/commit/475fe5df0e5b368400ef1fc3bc6ed277f8125172#diff-92a9c40963159c9d8f88fa2987057a65a2370737bd4ecc233498ebdfa02021e6L139

**Review by malfet — APPROVED** [review]

**Pull request merged**
