### PR TITLE
Dockerfile_cxx11-abi: change base image from ubuntu18.04 to centos8

### PR DESCRIPTION
**Pull request by guoyejun**
it is for backward compatibility to support more OSes.

### CODE REVIEW

**Comment by guoyejun** [comment]
any comment? thanks.

**Comment by guoyejun** [comment]
@malfet  any comment? thanks.

**Comment by guoyejun** [comment]
Hi @malfet  any comment for this change? thanks.

**Comment by guoyejun** [comment]
hi, is there any comment for this PR? thanks.

**Review by malfet — APPROVED** [review]

**Pull request merged**
