### PR TITLE
adding sm_86 to magma for cuda11.1 in cmakelists.patch

### PR DESCRIPTION
**Pull request by janeyx99**
CUDA 11.1 can now support sm_86.

### CODE REVIEW

**Comment by seemethere** [comment]
Does this patch still apply cleanly? I noticed you had removed a lot of whitespace.

**Comment by janeyx99** [comment]
My editor removes trailing whitespaces on save--does that mess with patches even though the new lines are preserved?

**Comment by seemethere** [comment]
> My editor removes trailing whitespaces on save--does that mess with patches even though the new lines are preserved?

It might, you should try to build it at least once to verify that it still functions as expected

**Comment by janeyx99** [comment]
Successfully ran locally and manually checked that the output looked the same (same files in subdirectories).

**Review by seemethere — APPROVED** [review]

**Pull request merged**
