### PR TITLE
Allow ROCm minor releases to use the same MIOpen branch as the major release

### PR DESCRIPTION
**Pull request by jithunnair-amd**

### CODE REVIEW

**Review by huydhn — APPROVED** [review]
LGTM! Let's see if 5.1.1 job passes. Thank you for the quick fix

**Comment by jithunnair-amd** [comment]
@huydhn ROCm5.1.1 job passed. ROCm5.2 was mysteriously cancelled (although I expect it to pass as well).

**Comment by huydhn** [comment]
All checks have passed. The PR looks good to me but as we are planning to have PyTorch 1.13 release this Thursday (Oct 27th).  I'll wait till Friday before merging this one to avoid pushing a new set of Docker images that can influence PyTorch binary release build.  Let me know if that's ok with you.  Thank you for your understanding!

**Comment by jithunnair-amd** [comment]
> All checks have passed. The PR looks good to me but as we are planning to have PyTorch 1.13 release this Thursday (Oct 27th). I'll wait till Friday before merging this one to avoid pushing a new set of Docker images that can influence PyTorch binary release build. Let me know if that's ok with you. Thank you for your understanding!

That should be okay since the primary ROCm version for PyTorch 1.13 release binaries would be ROCm5.2, which shouldn't be affected by the bug being fixed in this PR.

**Comment by jithunnair-amd** [comment]
@huydhn Good to go?

**Pull request merged**
