### PR TITLE
[Release-Only] Use triton pypi package for 2.1.0 release

### PR DESCRIPTION
**Pull request by huydhn**
This should fix https://github.com/pytorch/pytorch/issues/109221#issuecomment-1718138276 ~~in a safe way by just replacing `pytorch-triton` with `triton` package for release.~~

* torch-2.1.0+cu121.with.pypi.cudnn-cp310-cp310-linux_x86_64.whl should have:
```
Metadata-Version: 2.1
Name: torch
Version: 2.1.0+cu121.with.pypi.cudnn
...
Requires-Dist: filelock
Requires-Dist: typing-extensions
Requires-Dist: sympy
Requires-Dist: networkx
Requires-Dist: jinja2
Requires-Dist: fsspec
Requires-Dist: nvidia-cuda-nvrtc-cu12 (==12.1.105) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-cuda-runtime-cu12 (==12.1.105) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-cuda-cupti-cu12 (==12.1.105) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-cudnn-cu12 (==8.9.2.26) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-cublas-cu12 (==12.1.3.1) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-cufft-cu12 (==11.0.2.54) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-curand-cu12 (==10.3.2.106) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-cusolver-cu12 (==11.4.5.107) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-cusparse-cu12 (==12.1.0.106) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-nccl-cu12 (==2.18.1) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-nvtx-cu12 (==12.1.105) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: triton (==2.1.0) ; platform_system == "Linux" and platform_machine == "x86_64"
Provides-Extra: dynamo
Requires-Dist: jinja2 ; extra == 'dynamo'
Provides-Extra: opt-einsum
Requires-Dist: opt-einsum (>=3.3) ; extra == 'opt-einsum'
```

On the other hand, `pytorch-triton-rocm` package stay the same for ROCm release.

### CODE REVIEW

**Review by malfet — CHANGES_REQUESTED** [review]
I think one better delete this line altogether, as dependency should be `trition==2.1.0`, but `TRITON_VERSION` would be `2.1.0+e6216047b8`

**Comment by huydhn** [comment]
> I think one better delete this line altogether, as dependency should be `triton==2.1.0`, but `TRITON_VERSION` would be `2.1.0+e6216047b8`

The `TRITON_VERSION` is fine and will be the correct `2.1.0` for release.  The only concern I have is that I could only find `triton=2.1.0` set here https://github.com/pytorch/pytorch/pull/108423 for CUDA 12.1 (https://github.com/pytorch/pytorch/actions/runs/6162117011).  So, i'm trying to understand which one set it for 11.8

**Comment by huydhn** [comment]
Note: 12.1 should be fine because it has `triton` from https://github.com/pytorch/pytorch/pull/108423, but I'm a bit unclear about 11.8, which doesn't set `pytorch_extra_install_requirements` variable

`torch-2.1.0+cu118-cp310-cp310-linux_x86_64.whl` looks like this atm:
```
Metadata-Version: 2.1
Name: torch
Version: 2.1.0+cu118
...
Requires-Dist: filelock
Requires-Dist: typing-extensions
Requires-Dist: sympy
Requires-Dist: networkx
Requires-Dist: jinja2
Requires-Dist: fsspec
Requires-Dist: pytorch-triton (==2.1.0)
Provides-Extra: dynamo
Requires-Dist: jinja2 ; extra == 'dynamo'
Provides-Extra: opt-einsum
Requires-Dist: opt-einsum (>=3.3) ; extra == 'opt-einsum'
```

**Review by malfet — APPROVED** [review]
LGTM!

**Pull request merged**
