### PR TITLE
[aarch64] Adding CI Scripts to build aarch64 wheels

### PR DESCRIPTION
**Pull request by xncqr**
- Created the "aarch64_linux" foldering, moving aarch64 scripts to their own place.
- Moved build_aarch64_wheel.py from root to aarch64_linux folder
- Created Bash and Python scripts for future use in CI/CD building of PyTorch for aarch64
- Left build_aarch64_wheel.py intact as it has use for manual builds via AWS EC2 Instances

### CODE REVIEW

**Comment by xncqr** [comment]
@malfet can I get a review for this PR please?

**Comment by xncqr** [comment]
@malfet : merging of [PR=1309](https://github.com/pytorch/builder/pull/1309) caused conflict to this PR. [PR=1308](https://github.com/pytorch/builder/pull/1308) will do the same. Need to know if you are intending to work this PR or 1308 so I'm not trying to fix this conflict again.

**Comment by xncqr** [comment]
@malfet, fixed the merge conflict. able to have a look at this for the pipeline building?

**Comment by xncqr** [comment]
@malfet, just fix conflict after PR-1308 merge.. can I have this looked at and merged for supporting arm64_linux CI?

**Comment by malfet** [comment]
Can you please explain how one is supposed to test those changes?

**Comment by xncqr** [comment]
I'll make a readme.md on the files here. executing [aarch64_linux/aarch64_ci_build.sh](https://github.com/pytorch/builder/pull/1302/files#diff-728d3529944adaec87493597137677212e632ab37e079eec69eb277e491f3f14) with the same env variables that is done in the workflow, on a centos7 based, container (we are using pypi manylinux) would start the build. This is all done in the container which the workflow would start on the github agent.

you expecting the readme.md?

**Comment by xncqr** [comment]
Readme added, along with a couple more updates related to pulling the branch name from the repo supplied in /pytorch.

**Review by malfet — APPROVED** [review]

**Pull request merged**
