### PR TITLE
Add OPENSSL_ROOT_DIR to manywheel/build.sh

### PR DESCRIPTION
**Pull request by pbelevich**

### CODE REVIEW

**Comment by seemethere** [comment]
Is it possible to test this with a dummy PR to `pytorch/pytorch` that changes the line in https://github.com/pytorch/pytorch/blob/28a9483e360e8aaed01a603b29a569ded4c21b5b/.circleci/scripts/binary_checkout.sh#L64 to point to this branch?

Just curious to see if the change actually works and builds with the correct openssl versions.

Also is there a way to verify if it's built with the correct openssl verion?

**Comment by pbelevich** [comment]
> Also is there a way to verify if it's built with the correct openssl verion?
https://github.com/pytorch/pytorch/pull/56026 should pass CI

**Comment by pbelevich** [comment]
> Is it possible to test this with a dummy PR to `pytorch/pytorch` that changes the line in https://github.com/pytorch/pytorch/blob/28a9483e360e8aaed01a603b29a569ded4c21b5b/.circleci/scripts/binary_checkout.sh#L64 to point to this branch?

@seemethere https://github.com/pytorch/pytorch/pull/56936

**Comment by seemethere** [comment]
Superseded by #725

**Pull request closed without merging**
